# Generated by Django 5.1.6 on 2025-03-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('car_plate', models.CharField(max_length=7)),
                ('checkin_date', models.DateField()),
                ('checkin_time', models.TimeField()),
            ],
        ),
    ]
