# Generated by Django 5.1.6 on 2025-03-06 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField(default=False)),
                ('occupied_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_space', to='apps.car')),
            ],
        ),
    ]
