# Generated by Django 5.1.6 on 2025-03-06 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_autos_options_autosspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField(default=False)),
                ('occupied_by', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_space', to='apps.autos')),
            ],
        ),
        migrations.DeleteModel(
            name='AutosSpace',
        ),
    ]
