# Generated by Django 5.1.6 on 2025-03-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_carspace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('-checkin_time',)},
        ),
    ]
