# Generated by Django 5.1.6 on 2025-03-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='checkin_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='checkin_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
