# Generated by Django 5.1.6 on 2025-03-06 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_parkingspace_delete_autosspace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autos',
            options={'ordering': ('-checkin_datetime',), 'verbose_name': 'Autos', 'verbose_name_plural': 'Autos'},
        ),
        migrations.RemoveField(
            model_name='autos',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='autos',
            name='checkin_time',
        ),
        migrations.AddField(
            model_name='autos',
            name='checkin_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
