# Generated by Django 5.1.6 on 2025-03-06 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_autos_options_remove_autos_checkin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='last_users',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('cnh', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('file_upload', models.FileField(blank=True, upload_to='uploaded_files')),
                ('auto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='apps.autos')),
            ],
        ),
    ]
