# Generated by Django 5.1.6 on 2025-03-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_car_checkin_date_alter_car_checkin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='checkout_time',
            field=models.TimeField(blank=True, default='HH:MM'),
        ),
    ]
