# Generated by Django 5.1.6 on 2025-03-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_car_checkout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='checkout_time',
            field=models.TimeField(blank=True, default='00:00'),
        ),
    ]
