# Generated by Django 5.1.6 on 2025-03-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_parkingspace_last_users_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='auto',
        ),
        migrations.AddField(
            model_name='driver',
            name='auto',
            field=models.ManyToManyField(to='apps.autos'),
        ),
    ]
