# Generated by Django 5.1.6 on 2025-03-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_car_checkout_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='checkout_time',
        ),
    ]
