# Generated by Django 5.1.6 on 2025-03-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_driver_auto_driver_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
    ]
