# Generated by Django 5.1.6 on 2025-03-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_parkingspace_last_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='parked',
            field=models.BooleanField(default=False),
        ),
    ]
