# Generated by Django 5.1.6 on 2025-03-07 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_autos_parked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='auto',
        ),
        migrations.AddField(
            model_name='autos',
            name='driver_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apps.driver'),
        ),
    ]
