# Generated by Django 5.1.6 on 2025-03-07 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_remove_driver_auto_autos_driver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='last_users',
        ),
    ]
