# Generated by Django 5.1.6 on 2025-03-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_remove_parkingspace_last_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='history',
            field=models.JSONField(default=None),
        ),
    ]
