# Generated by Django 5.1.6 on 2025-03-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_parkingspace_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='history',
            field=models.JSONField(default=None, null=True),
        ),
    ]
