# Generated by Django 5.1.6 on 2025-03-07 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_parkingspace_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='occupied_by',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.SET_DEFAULT, to='apps.autos'),
        ),
    ]
