# Generated by Django 5.1.6 on 2025-03-07 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_parkingspace_occupied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='occupied_by',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.autos'),
        ),
    ]
