# Generated by Django 5.1.6 on 2025-03-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_parkingspace_occupied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='checkin_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='history',
            field=models.JSONField(default={'autos_plate': '', 'checkin_datetime': '', 'checkout_datetime': '', 'model': ''}, null=True),
        ),
    ]
