# Generated by Django 5.1.6 on 2025-03-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_autos_checkin_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='history',
            field=models.JSONField(default={}, null=True),
        ),
    ]
