# Generated by Django 5.1.6 on 2025-03-27 03:51

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_alter_parkingspace_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='history',
            field=models.JSONField(default=apps.models.ParkingSpace.create_list, null=True),
        ),
    ]
