# Generated by Django 5.1.6 on 2025-03-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_alter_parkingspace_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autos',
            old_name='driver_name',
            new_name='driver',
        ),
    ]
